"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import sys
import typing
import yandex.cloud.operation.operation_pb2
import yandex.cloud.vpc.v1.security_group_pb2

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetSecurityGroupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["security_group_id", b"security_group_id"]) -> None: ...

global___GetSecurityGroupRequest = GetSecurityGroupRequest

class ListSecurityGroupsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOLDER_ID_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    FILTER_FIELD_NUMBER: builtins.int
    folder_id: builtins.str
    page_size: builtins.int
    page_token: builtins.str
    filter: builtins.str
    """filter by network_id is here"""
    def __init__(
        self,
        *,
        folder_id: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
        filter: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filter", b"filter", "folder_id", b"folder_id", "page_size", b"page_size", "page_token", b"page_token"]) -> None: ...

global___ListSecurityGroupsRequest = ListSecurityGroupsRequest

class ListSecurityGroupsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUPS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def security_groups(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[yandex.cloud.vpc.v1.security_group_pb2.SecurityGroup]: ...
    next_page_token: builtins.str
    def __init__(
        self,
        *,
        security_groups: collections.abc.Iterable[yandex.cloud.vpc.v1.security_group_pb2.SecurityGroup] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token", b"next_page_token", "security_groups", b"security_groups"]) -> None: ...

global___ListSecurityGroupsResponse = ListSecurityGroupsResponse

class CreateSecurityGroupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    FOLDER_ID_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    NETWORK_ID_FIELD_NUMBER: builtins.int
    RULE_SPECS_FIELD_NUMBER: builtins.int
    folder_id: builtins.str
    name: builtins.str
    description: builtins.str
    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    network_id: builtins.str
    @property
    def rule_specs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SecurityGroupRuleSpec]: ...
    def __init__(
        self,
        *,
        folder_id: builtins.str = ...,
        name: builtins.str = ...,
        description: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        network_id: builtins.str = ...,
        rule_specs: collections.abc.Iterable[global___SecurityGroupRuleSpec] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "folder_id", b"folder_id", "labels", b"labels", "name", b"name", "network_id", b"network_id", "rule_specs", b"rule_specs"]) -> None: ...

global___CreateSecurityGroupRequest = CreateSecurityGroupRequest

class SecurityGroupRuleSpec(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    DESCRIPTION_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    PORTS_FIELD_NUMBER: builtins.int
    PROTOCOL_NAME_FIELD_NUMBER: builtins.int
    PROTOCOL_NUMBER_FIELD_NUMBER: builtins.int
    CIDR_BLOCKS_FIELD_NUMBER: builtins.int
    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    PREDEFINED_TARGET_FIELD_NUMBER: builtins.int
    description: builtins.str
    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    direction: yandex.cloud.vpc.v1.security_group_pb2.SecurityGroupRule.Direction.ValueType
    @property
    def ports(self) -> yandex.cloud.vpc.v1.security_group_pb2.PortRange:
        """null value means any port"""
    protocol_name: builtins.str
    protocol_number: builtins.int
    @property
    def cidr_blocks(self) -> yandex.cloud.vpc.v1.security_group_pb2.CidrBlocks: ...
    security_group_id: builtins.str
    predefined_target: builtins.str
    """string subnet_id = .. ;"""
    def __init__(
        self,
        *,
        description: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        direction: yandex.cloud.vpc.v1.security_group_pb2.SecurityGroupRule.Direction.ValueType = ...,
        ports: yandex.cloud.vpc.v1.security_group_pb2.PortRange | None = ...,
        protocol_name: builtins.str = ...,
        protocol_number: builtins.int = ...,
        cidr_blocks: yandex.cloud.vpc.v1.security_group_pb2.CidrBlocks | None = ...,
        security_group_id: builtins.str = ...,
        predefined_target: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["cidr_blocks", b"cidr_blocks", "ports", b"ports", "predefined_target", b"predefined_target", "protocol", b"protocol", "protocol_name", b"protocol_name", "protocol_number", b"protocol_number", "security_group_id", b"security_group_id", "target", b"target"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["cidr_blocks", b"cidr_blocks", "description", b"description", "direction", b"direction", "labels", b"labels", "ports", b"ports", "predefined_target", b"predefined_target", "protocol", b"protocol", "protocol_name", b"protocol_name", "protocol_number", b"protocol_number", "security_group_id", b"security_group_id", "target", b"target"]) -> None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["protocol", b"protocol"]) -> typing_extensions.Literal["protocol_name", "protocol_number"] | None: ...
    @typing.overload
    def WhichOneof(self, oneof_group: typing_extensions.Literal["target", b"target"]) -> typing_extensions.Literal["cidr_blocks", "security_group_id", "predefined_target"] | None: ...

global___SecurityGroupRuleSpec = SecurityGroupRuleSpec

class CreateSecurityGroupMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["security_group_id", b"security_group_id"]) -> None: ...

global___CreateSecurityGroupMetadata = CreateSecurityGroupMetadata

class UpdateSecurityGroupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    RULE_SPECS_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    name: builtins.str
    description: builtins.str
    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def rule_specs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SecurityGroupRuleSpec]:
        """all existing rules will be replaced with given list"""
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        name: builtins.str = ...,
        description: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        rule_specs: collections.abc.Iterable[global___SecurityGroupRuleSpec] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "labels", b"labels", "name", b"name", "rule_specs", b"rule_specs", "security_group_id", b"security_group_id", "update_mask", b"update_mask"]) -> None: ...

global___UpdateSecurityGroupRequest = UpdateSecurityGroupRequest

class UpdateSecurityGroupMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    ADDED_RULE_IDS_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    @property
    def added_rule_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
        added_rule_ids: collections.abc.Iterable[builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["added_rule_ids", b"added_rule_ids", "security_group_id", b"security_group_id"]) -> None: ...

global___UpdateSecurityGroupMetadata = UpdateSecurityGroupMetadata

class UpdateSecurityGroupRulesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    DELETION_RULE_IDS_FIELD_NUMBER: builtins.int
    ADDITION_RULE_SPECS_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    @property
    def deletion_rule_ids(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """list of rules ids to delete"""
    @property
    def addition_rule_specs(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SecurityGroupRuleSpec]: ...
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
        deletion_rule_ids: collections.abc.Iterable[builtins.str] | None = ...,
        addition_rule_specs: collections.abc.Iterable[global___SecurityGroupRuleSpec] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["addition_rule_specs", b"addition_rule_specs", "deletion_rule_ids", b"deletion_rule_ids", "security_group_id", b"security_group_id"]) -> None: ...

global___UpdateSecurityGroupRulesRequest = UpdateSecurityGroupRulesRequest

class UpdateSecurityGroupRuleRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class LabelsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "value", b"value"]) -> None: ...

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    RULE_ID_FIELD_NUMBER: builtins.int
    UPDATE_MASK_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    rule_id: builtins.str
    @property
    def update_mask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    description: builtins.str
    @property
    def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
        rule_id: builtins.str = ...,
        update_mask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        description: builtins.str = ...,
        labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["update_mask", b"update_mask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["description", b"description", "labels", b"labels", "rule_id", b"rule_id", "security_group_id", b"security_group_id", "update_mask", b"update_mask"]) -> None: ...

global___UpdateSecurityGroupRuleRequest = UpdateSecurityGroupRuleRequest

class UpdateSecurityGroupRuleMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    RULE_ID_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    rule_id: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
        rule_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["rule_id", b"rule_id", "security_group_id", b"security_group_id"]) -> None: ...

global___UpdateSecurityGroupRuleMetadata = UpdateSecurityGroupRuleMetadata

class DeleteSecurityGroupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["security_group_id", b"security_group_id"]) -> None: ...

global___DeleteSecurityGroupRequest = DeleteSecurityGroupRequest

class DeleteSecurityGroupMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["security_group_id", b"security_group_id"]) -> None: ...

global___DeleteSecurityGroupMetadata = DeleteSecurityGroupMetadata

class ListSecurityGroupOperationsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    PAGE_SIZE_FIELD_NUMBER: builtins.int
    PAGE_TOKEN_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    page_size: builtins.int
    page_token: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
        page_size: builtins.int = ...,
        page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["page_size", b"page_size", "page_token", b"page_token", "security_group_id", b"security_group_id"]) -> None: ...

global___ListSecurityGroupOperationsRequest = ListSecurityGroupOperationsRequest

class ListSecurityGroupOperationsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OPERATIONS_FIELD_NUMBER: builtins.int
    NEXT_PAGE_TOKEN_FIELD_NUMBER: builtins.int
    @property
    def operations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[yandex.cloud.operation.operation_pb2.Operation]: ...
    next_page_token: builtins.str
    def __init__(
        self,
        *,
        operations: collections.abc.Iterable[yandex.cloud.operation.operation_pb2.Operation] | None = ...,
        next_page_token: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["next_page_token", b"next_page_token", "operations", b"operations"]) -> None: ...

global___ListSecurityGroupOperationsResponse = ListSecurityGroupOperationsResponse

class MoveSecurityGroupRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    DESTINATION_FOLDER_ID_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    destination_folder_id: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
        destination_folder_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["destination_folder_id", b"destination_folder_id", "security_group_id", b"security_group_id"]) -> None: ...

global___MoveSecurityGroupRequest = MoveSecurityGroupRequest

class MoveSecurityGroupMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECURITY_GROUP_ID_FIELD_NUMBER: builtins.int
    security_group_id: builtins.str
    def __init__(
        self,
        *,
        security_group_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["security_group_id", b"security_group_id"]) -> None: ...

global___MoveSecurityGroupMetadata = MoveSecurityGroupMetadata
