"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing
import typing_extensions
import yandex.cloud.cdn.v1.origin_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class GetOriginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FOLDER_ID_FIELD_NUMBER: builtins.int
    ORIGIN_ID_FIELD_NUMBER: builtins.int
    folder_id: typing.Text
    """ID of the folder that the origin belongs to."""

    origin_id: builtins.int
    """[origin_id] group ID to request origin from."""

    def __init__(self,
        *,
        folder_id: typing.Text = ...,
        origin_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["folder_id",b"folder_id","origin_id",b"origin_id"]) -> None: ...
global___GetOriginRequest = GetOriginRequest

class ListOriginsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FOLDER_ID_FIELD_NUMBER: builtins.int
    ORIGIN_GROUP_ID_FIELD_NUMBER: builtins.int
    folder_id: typing.Text
    """ID of the folder that the origin belongs to."""

    origin_group_id: builtins.int
    """ID of the group to request origins from."""

    def __init__(self,
        *,
        folder_id: typing.Text = ...,
        origin_group_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["folder_id",b"folder_id","origin_group_id",b"origin_group_id"]) -> None: ...
global___ListOriginsRequest = ListOriginsRequest

class ListOriginsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORIGINS_FIELD_NUMBER: builtins.int
    @property
    def origins(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[yandex.cloud.cdn.v1.origin_pb2.Origin]:
        """Origin from response."""
        pass
    def __init__(self,
        *,
        origins: typing.Optional[typing.Iterable[yandex.cloud.cdn.v1.origin_pb2.Origin]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["origins",b"origins"]) -> None: ...
global___ListOriginsResponse = ListOriginsResponse

class CreateOriginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FOLDER_ID_FIELD_NUMBER: builtins.int
    ORIGIN_GROUP_ID_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    BACKUP_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    folder_id: typing.Text
    """ID of the folder that the origin belongs to."""

    origin_group_id: builtins.int
    """[origin_group_id] group ID to request origins from."""

    source: typing.Text
    """IP address or Domain name of your origin and the port (if custom).
    Used if [meta] variant is `common`.
    """

    @property
    def enabled(self) -> google.protobuf.wrappers_pb2.BoolValue:
        """The setting allows to enable or disable an Origin source in the Origins group.

        It has two possible values:

        True - The origin is enabled and used as a source for the CDN. An origins
        group must contain at least one enabled origin. Default value.
        False - The origin is disabled and the CDN is not using it to pull content.
        """
        pass
    @property
    def backup(self) -> google.protobuf.wrappers_pb2.BoolValue:
        """Specifies whether the origin is used in its origin group as backup. 
        A backup origin is used when one of active origins becomes unavailable.

        Default value: False.
        """
        pass
    @property
    def meta(self) -> yandex.cloud.cdn.v1.origin_pb2.OriginMeta:
        """Set up origin of the content."""
        pass
    def __init__(self,
        *,
        folder_id: typing.Text = ...,
        origin_group_id: builtins.int = ...,
        source: typing.Text = ...,
        enabled: typing.Optional[google.protobuf.wrappers_pb2.BoolValue] = ...,
        backup: typing.Optional[google.protobuf.wrappers_pb2.BoolValue] = ...,
        meta: typing.Optional[yandex.cloud.cdn.v1.origin_pb2.OriginMeta] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["backup",b"backup","enabled",b"enabled","meta",b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["backup",b"backup","enabled",b"enabled","folder_id",b"folder_id","meta",b"meta","origin_group_id",b"origin_group_id","source",b"source"]) -> None: ...
global___CreateOriginRequest = CreateOriginRequest

class CreateOriginMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORIGIN_ID_FIELD_NUMBER: builtins.int
    ORIGIN_GROUP_ID_FIELD_NUMBER: builtins.int
    origin_id: builtins.int
    """ID of the origin."""

    origin_group_id: builtins.int
    """ID pf the parent origins group."""

    def __init__(self,
        *,
        origin_id: builtins.int = ...,
        origin_group_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["origin_group_id",b"origin_group_id","origin_id",b"origin_id"]) -> None: ...
global___CreateOriginMetadata = CreateOriginMetadata

class UpdateOriginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FOLDER_ID_FIELD_NUMBER: builtins.int
    ORIGIN_ID_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    ENABLED_FIELD_NUMBER: builtins.int
    BACKUP_FIELD_NUMBER: builtins.int
    META_FIELD_NUMBER: builtins.int
    folder_id: typing.Text
    """ID of the folder that the origin belongs to."""

    origin_id: builtins.int
    """ID of the origin."""

    source: typing.Text
    """PUT behavior, parameter below will be fully rewritten

    IP address or Domain name of your origin and the port (if custom).
    Used if [meta] variant is `common`.
    Required.
    """

    enabled: builtins.bool
    """The setting allows to enable or disable an Origin source in the Origins group.

    It has two possible values:

    True - The origin is enabled and used as a source for the CDN. An origins
    group must contain at least one enabled origin. Default value.
    False - The origin is disabled and the CDN is not using it to pull content.

    Required.
    """

    backup: builtins.bool
    """Specifies whether the origin is used in its origin group as backup. 
    A backup origin is used when one of active origins becomes unavailable.

    Required.
    """

    @property
    def meta(self) -> yandex.cloud.cdn.v1.origin_pb2.OriginMeta:
        """Set up type of the origin."""
        pass
    def __init__(self,
        *,
        folder_id: typing.Text = ...,
        origin_id: builtins.int = ...,
        source: typing.Text = ...,
        enabled: builtins.bool = ...,
        backup: builtins.bool = ...,
        meta: typing.Optional[yandex.cloud.cdn.v1.origin_pb2.OriginMeta] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["meta",b"meta"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["backup",b"backup","enabled",b"enabled","folder_id",b"folder_id","meta",b"meta","origin_id",b"origin_id","source",b"source"]) -> None: ...
global___UpdateOriginRequest = UpdateOriginRequest

class UpdateOriginMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORIGIN_ID_FIELD_NUMBER: builtins.int
    ORIGIN_GROUP_ID_FIELD_NUMBER: builtins.int
    origin_id: builtins.int
    """ID of the origin."""

    origin_group_id: builtins.int
    """Parent origins group ID."""

    def __init__(self,
        *,
        origin_id: builtins.int = ...,
        origin_group_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["origin_group_id",b"origin_group_id","origin_id",b"origin_id"]) -> None: ...
global___UpdateOriginMetadata = UpdateOriginMetadata

class DeleteOriginRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FOLDER_ID_FIELD_NUMBER: builtins.int
    ORIGIN_ID_FIELD_NUMBER: builtins.int
    folder_id: typing.Text
    """ID of the folder that the origin belongs to."""

    origin_id: builtins.int
    """ID of the origin."""

    def __init__(self,
        *,
        folder_id: typing.Text = ...,
        origin_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["folder_id",b"folder_id","origin_id",b"origin_id"]) -> None: ...
global___DeleteOriginRequest = DeleteOriginRequest

class DeleteOriginMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    ORIGIN_ID_FIELD_NUMBER: builtins.int
    origin_id: builtins.int
    """ID of the origin."""

    def __init__(self,
        *,
        origin_id: builtins.int = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["origin_id",b"origin_id"]) -> None: ...
global___DeleteOriginMetadata = DeleteOriginMetadata
