name: Update stubs

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  update-stubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Generate stubs
        id: generate
        run: |
          make deps
          make clone
          make proto
          
          git config --global user.name 'q0w'
          git config --global user.email '43147888+q0w@users.noreply.github.com'
          git add yandex
          git commit -m 'regenerate stubs' || echo "No changes in .proto files found"
          git push    
